name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main
      - feat/containarization_and_pipelines
  push:
    branches:
      - main
      - feat/containarization_and_pipelines
    paths:
    #   - Dockerfile
    #   - pyproject.toml
    #   - main.py
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops_reddit_scrapper:latest